"""Implementation-plan prompt -- derives a phased migration plan."""

from __future__ import annotations

from pathlib import Path

from ._helpers import _target_file_instruction, _template_section, _draft_status


def build_implementation_plan_prompt(
    config: dict, program: str | None = None, *, workspace: Path | None = None
) -> str:
    output_dir = config.get("output", "./output")
    output_files = [
        f"{output_dir}/requirements/implementation-plan.md",
    ]
    draft_section = _draft_status(output_files, workspace) if workspace else ""
    return (
        "You are a migration architect creating a phased implementation plan "
        "for migrating a COBOL application to a modern platform. Your plan must "
        "be grounded in the reverse-engineering artifacts, not generic advice. "
        "You must evaluate the codebase characteristics and select the most "
        "appropriate migration strategy before designing the plan.\n\n"
        "## Migration Strategies\n\n"
        "There is no one-size-fits-all migration approach. Evaluate these "
        "strategies against the actual codebase:\n\n"
        "### Strangler Fig (Hollow-Out)\n\n"
        "Incrementally extract capabilities by intercepting traffic at natural "
        "seams. The old system keeps running throughout; each phase extracts one "
        "or more capabilities, validates correctness, then cuts over.\n\n"
        "**Best when:** Large codebase (10+ programs), mix of online and batch, "
        "identifiable integration seams exist, business cannot tolerate extended "
        "cutover downtime.\n\n"
        "**Avoid when:** System is too tightly coupled for seam placement, "
        "codebase is small enough that coexistence overhead exceeds rewrite cost, "
        "or system is batch-only with no online transaction routing.\n\n"
        "### Rewrite\n\n"
        "Clean rebuild of the system on a modern platform with a single cutover.\n\n"
        "**Best when:** Small codebase (<5 programs, <5k LOC), well-understood "
        "requirements, low coupling to external systems, team has strong domain "
        "knowledge.\n\n"
        "**Avoid when:** Large codebase (risk of second-system effect), poor "
        "requirements documentation, many external integrations that must be "
        "maintained during development.\n\n"
        "### Branch-by-Abstraction\n\n"
        "Introduce abstraction layers inside the monolith first (e.g., wrap "
        "data access, extract interfaces for CALL targets), then swap "
        "implementations behind those abstractions.\n\n"
        "**Best when:** Tightly coupled system with no natural seams, heavy use "
        "of shared copybooks and REDEFINES, programs communicate via shared "
        "working storage rather than clean CALL interfaces.\n\n"
        "**Avoid when:** Natural seams already exist (strangler fig is simpler), "
        "system is small enough to rewrite.\n\n"
        "### Parallel Run\n\n"
        "Build the new system, then run both old and new in parallel -- comparing "
        "outputs for a validation period before cutover.\n\n"
        "**Best when:** High regulatory or financial risk, compliance requires "
        "proof of equivalence, batch processing where input/output comparison "
        "is straightforward.\n\n"
        "**Avoid when:** Online systems with side effects that cannot be safely "
        "duplicated, systems where running two copies doubles infrastructure "
        "cost prohibitively.\n\n"
        "### Pipeline Replacement\n\n"
        "Replace batch pipeline steps (JCL job steps, sort/merge/extract chains) "
        "individually, validating each step's output before moving to the next.\n\n"
        "**Best when:** Batch-only system, clear step boundaries in JCL, "
        "steps communicate via sequential files, no online transaction routing "
        "needed.\n\n"
        "**Avoid when:** System has online components, steps are tightly coupled "
        "via shared in-memory state.\n\n"
        "## Strategy Selection Framework\n\n"
        "Evaluate these codebase signals to select a strategy:\n\n"
        "| Signal | Assessment | Implications |\n"
        "| --- | --- | --- |\n"
        "| Scale (program count, LOC) | Small (<5 programs) vs Large (10+) | "
        "Small favours Rewrite; Large favours Strangler Fig or Branch-by-Abstraction |\n"
        "| Online/batch mix | Online-heavy, batch-heavy, or mixed | "
        "Batch-only favours Pipeline Replacement; online or mixed favours Strangler Fig |\n"
        "| Coupling level | Shared copybooks, CALL density, shared data | "
        "High coupling with no seams favours Branch-by-Abstraction |\n"
        "| Natural seams | CALL boundaries, file I/O, MQ, CICS routing | "
        "Clear seams favour Strangler Fig; absent seams favour Branch-by-Abstraction |\n"
        "| Regulatory/risk profile | Financial accuracy, audit requirements | "
        "High regulatory risk may require Parallel Run regardless of other factors |\n"
        "| Data architecture | Shared vs isolated data stores | "
        "Shared data increases coexistence complexity for all strategies |\n"
        "| Business continuity | Tolerance for downtime during cutover | "
        "Zero-downtime requirement favours Strangler Fig over Rewrite |\n\n"
        "A hybrid approach is valid -- for example, Strangler Fig for online "
        "capabilities with Pipeline Replacement for batch, or Branch-by-Abstraction "
        "as a preparatory phase before Strangler Fig extraction.\n\n"
        "## Strategy-Specific Planning Guidance\n\n"
        "### Strangler Fig Details\n\n"
        "#### Seam Types\n\n"
        "| Integration Pattern in COBOL | Strangler Seam Type |\n"
        "| --- | --- |\n"
        "| CALL/LINK between programs | API boundary -- replace CALL with service call via adapter |\n"
        "| File-based I/O (VSAM, flat files) | Event/message boundary -- intercept with file watcher or MQ |\n"
        "| CICS screen maps (BMS) | UI boundary -- replace screens with new frontend, keep backend |\n"
        "| DB2 table access | Database view/API boundary -- abstract via data access layer |\n"
        "| MQ PUT/GET | Already event-driven -- easiest seam, just reroute queues |\n"
        "| JCL job step sequences | Pipeline boundary -- replace individual steps |\n"
        "| EXEC CICS LINK/XCTL | Transaction boundary -- intercept at CICS routing level |\n\n"
        "#### Phase Ordering Heuristics\n\n"
        "| Signal | Ordering Strategy |\n"
        "| --- | --- |\n"
        "| Leaf programs (no callers) | Extract early -- minimal disruption, no upstream impact |\n"
        "| Batch-only capabilities | Extract early -- simpler coexistence (no real-time routing) |\n"
        "| Low cyclomatic complexity | Extract early -- lower risk, builds team confidence |\n"
        "| Self-contained data (own files/tables, not shared) | Extract early -- no data sync needed |\n"
        "| High business value + low complexity | Extract early -- quick wins demonstrate value |\n"
        "| Hub programs (many callers) | Extract late -- requires upstream migration first |\n"
        "| Shared copybook users (5+ programs) | Extract together or late -- tight coupling |\n"
        "| CICS online transactions | Extract mid-to-late -- requires routing infrastructure |\n"
        "| Programs with complex REDEFINES | Extract late -- semantic translation risk |\n"
        "| Programs with dynamic CALLs | Extract late -- hard to trace all callers |\n\n"
        "### Rewrite Details\n\n"
        "- Define clear acceptance criteria from test-specs before starting\n"
        "- Map every business rule to a test that must pass in the new system\n"
        "- Plan a single cutover window with a tested rollback procedure\n"
        "- Build data migration scripts with validation checksums\n"
        "- Run parallel comparison tests before the cutover date\n\n"
        "### Branch-by-Abstraction Details\n\n"
        "- Phase 1: Identify coupling points (shared copybooks, inline SQL, "
        "direct file I/O)\n"
        "- Phase 2: Introduce abstraction wrappers within the COBOL system "
        "(e.g., centralise file I/O through a single CALL, extract shared data "
        "access into service programs)\n"
        "- Phase 3: Once abstractions are stable, swap implementations behind "
        "them to modern equivalents\n"
        "- Phase 4: Remove COBOL implementations as modern equivalents prove "
        "stable\n\n"
        "### Parallel Run Details\n\n"
        "- Build the new system to completion before starting parallel operation\n"
        "- Define output comparison criteria (exact match, tolerance-based, "
        "semantic equivalence)\n"
        "- Establish a minimum parallel run duration based on business cycle "
        "(monthly close, quarter-end, year-end)\n"
        "- Automate comparison reporting with exception alerting\n"
        "- Define clear go/no-go criteria for cutover\n\n"
        "### Pipeline Replacement Details\n\n"
        "- Map the full JCL job stream with inputs and outputs per step\n"
        "- Replace steps from the outside in (first and last steps first, "
        "working inward)\n"
        "- Validate each replaced step by comparing output files byte-for-byte "
        "or field-by-field\n"
        "- Use file-level intercepts (write old output, compare with new output) "
        "during transition\n\n"
        "## Data Coexistence Patterns\n\n"
        "Applicable to any strategy that involves a coexistence period:\n\n"
        "| Pattern | When to Use | Complexity |\n"
        "| --- | --- | --- |\n"
        "| Shared database (both systems read/write) | Early phases, read-heavy workloads | Low |\n"
        "| Dual-write (write to both old and new) | During transition, when both systems are active | Medium |\n"
        "| Change Data Capture (CDC) | Large data volumes, eventual consistency acceptable | Medium |\n"
        "| Database-per-service with sync | Post-extraction, clean separation needed | High |\n"
        "| Event sourcing | New system design allows it, audit trail important | High |\n\n"
        "## Risk Assessment Framework\n\n"
        "For each migration phase, assess:\n"
        "- **Data integrity risk**: Does this phase split a transaction boundary? "
        "Are there compensating transactions needed?\n"
        "- **Performance risk**: Does the approach introduce network hops? "
        "Is there a latency-sensitive path?\n"
        "- **Rollback risk**: Can you revert if the phase fails? "
        "How long to switch back?\n"
        "- **Coupling risk**: How many other programs depend on what you are changing? "
        "Are there hidden dependencies (shared copybooks, implicit file contracts)?\n\n"
        "## Instructions\n\n"
        "1. **Read all existing output artifacts:**\n"
        f"   - {output_dir}/requirements/capabilities.md for capability groupings "
        "(these become your extraction/rebuild units)\n"
        f"   - {output_dir}/requirements/modernization-notes.md for risks, "
        "complexity, decomposition candidates, and patterns\n"
        f"   - {output_dir}/requirements/non-functional.md for NFRs that constrain "
        "migration (error handling, recovery, performance)\n"
        f"   - {output_dir}/flows/program-call-graph.md for dependency topology "
        "(find leaf vs hub programs)\n"
        f"   - {output_dir}/flows/data-flows.md for data movement patterns "
        "(identify shared data stores)\n"
        f"   - {output_dir}/integration/interfaces.md for external boundaries "
        "(these are natural seams)\n"
        f"   - {output_dir}/integration/io-map.md for per-program I/O counts\n"
        f"   - {output_dir}/inventory/programs.md for program types and LOC\n"
        f"   - {output_dir}/data/data-dictionary.md for shared data structures\n"
        f"   - {output_dir}/data/file-layouts.md for file dependencies\n"
        f"   - {output_dir}/data/database-operations.md for DB coupling\n"
        f"   - {output_dir}/business-rules/*.md for per-program complexity\n"
        f"   - {output_dir}/application.md for overall application context\n\n"
        "2. **Evaluate and select a migration strategy:**\n"
        "   - Assess each signal in the Strategy Selection Framework using data "
        "from the artifacts\n"
        "   - Score each strategy's fit for this specific codebase\n"
        "   - Select the best strategy (or hybrid) with a clear rationale\n"
        "   - Document the evaluation in the Strategy Evaluation section\n\n"
        "3. **Analyse boundaries and dependencies:**\n"
        "   - For Strangler Fig: identify seams using the Seam Types table\n"
        "   - For Branch-by-Abstraction: identify coupling points to wrap\n"
        "   - For Pipeline Replacement: map JCL step boundaries\n"
        "   - For Rewrite: identify data migration and integration touchpoints\n"
        "   - For Parallel Run: identify output comparison points\n"
        "   - For all strategies: identify data stores and their sharing patterns\n\n"
        "4. **Design migration phases:**\n"
        "   - Phase 0 is always Foundation: infrastructure, observability, "
        "rollback mechanism, and any coexistence plumbing\n"
        "   - Map each capability from capabilities.md to a phase\n"
        "   - Apply strategy-appropriate ordering heuristics\n"
        "   - For each phase, specify: what moves, how coexistence works, "
        "and how to roll back\n"
        "   - Never split a capability across phases unless it is very large "
        "(10+ programs)\n"
        "   - Consider batch and online programs separately when they belong to "
        "the same capability -- batch can often move first\n\n"
        "5. **Define the data migration strategy:**\n"
        "   - For each data store (VSAM file, DB2 table, IMS segment), decide "
        "when and how it migrates\n"
        "   - Shared data stores need a coexistence pattern from the table above\n"
        "   - Data stores used only by programs in one phase can migrate with "
        "that phase\n\n"
        "6. **Describe the coexistence architecture** (if applicable):\n"
        "   - Routing: how requests reach the right system during transition\n"
        "   - Transactions: how to maintain consistency across old and new\n"
        "   - Data sync: how shared data stays consistent\n"
        "   - Omit this section for strategies with no coexistence period "
        "(e.g., single-cutover Rewrite)\n\n"
        "7. **Build the risk register:**\n"
        "   - One row per identified risk, tied to a specific phase\n"
        "   - Use the Risk Assessment Framework\n"
        "   - Include mitigation strategies\n\n"
        "8. **Create the dependency graph:**\n"
        "   - Mermaid diagram showing phase dependencies\n"
        "   - Phases that can run in parallel should not have edges between them\n\n"
        "9. **Write the implementation plan** to:\n"
        f"   - {output_dir}/requirements/implementation-plan.md\n\n"
        "   Update the frontmatter `total_phases` field with the actual phase count.\n"
        "   Update `strategy` with the selected strategy "
        "(strangler-fig | rewrite | branch-by-abstraction | parallel-run | "
        "pipeline-replacement | hybrid).\n\n"
        f"{_target_file_instruction(f'{output_dir}/requirements/implementation-plan.md', cross_cutting=True)}\n\n"
        "## Output Structure Reference\n\n"
        "Follow these canonical section headers and table columns:\n\n"
        f"{_template_section('implementation-plan.md', f'{output_dir}/requirements/implementation-plan.md')}\n\n"
        f"{draft_section}\n\n"
        "10. **Return discoveries** as JSON array.\n\n"
        "Return ONLY a JSON array (no markdown fences) of discovery objects with:\n"
        "discovery_type, artifact_type, artifact_path, summary, confidence"
    )
