"""Requirements-deriver prompt -- synthesizes capabilities and modernization notes."""

from __future__ import annotations

from pathlib import Path

from ._helpers import _target_file_instruction, _template_section, _draft_status


def build_requirements_prompt(config: dict, program: str | None = None, *, workspace: Path | None = None) -> str:
    output_dir = config.get("output", "./output")
    output_files = [
        f"{output_dir}/requirements/capabilities.md",
        f"{output_dir}/requirements/non-functional.md",
        f"{output_dir}/requirements/modernization-notes.md",
        f"{output_dir}/application.md",
    ]
    draft_section = _draft_status(output_files, workspace) if workspace else ""
    return (
        "You are a requirements analyst synthesizing COBOL analysis outputs "
        "into business capabilities and modernization observations.\n\n"
        "## Capability Grouping Heuristics\n\n"
        "| Signal | Grouping Strategy |\n"
        "| --- | --- |\n"
        "| Programs that share copybooks | Likely part of the same capability |\n"
        "| Programs linked by CALL chains | Part of a single transaction/process |\n"
        "| Programs that read/write the same files | Part of a data pipeline |\n"
        "| JCL job steps | Steps within a single business process |\n"
        "| CICS transactions on the same map | Part of a single user interaction |\n\n"
        "## Non-Functional Requirement Indicators\n\n"
        "| NFR Category | What to look for in COBOL source |\n"
        "| --- | --- |\n"
        "| Error handling | ABEND calls vs graceful error paths, FILE STATUS checks, SQLCODE handling |\n"
        "| Data integrity | SYNCPOINT/COMMIT patterns, transaction boundaries, compare-before-write |\n"
        "| Performance | SORT steps, buffer sizes, block sizes, batch checkpoint intervals |\n"
        "| Security | Authorization checks, user ID validation, access control fields |\n"
        "| Audit/logging | DISPLAY statements, audit trail WRITE operations, timestamps |\n"
        "| Recovery | Restart/checkpoint logic, intermediate commit points in batch |\n\n"
        "## Modernization Risk Indicators\n\n"
        "| Risk Factor | What it means |\n"
        "| --- | --- |\n"
        "| GOTO-heavy programs | Complex control flow, hard to decompose |\n"
        "| Large shared copybooks (5+ users) | Tight coupling, schema change risk |\n"
        "| Complex REDEFINES chains | Memory overlay semantics, no direct equivalent in modern languages |\n"
        "| Dead code / commented-out sections | Technical debt, unclear intent |\n"
        "| Dynamic CALL (variable targets) | Runtime routing, harder to trace statically |\n"
        "| PERFORM THRU with fall-through | Implicit control flow, easy to misinterpret |\n\n"
        "## Confidence Rules\n\n"
        "- `high`: capability clearly supported by multiple consistent business rules across programs\n"
        "- `medium`: capability inferred from data flows and program names, but rules are complex or ambiguous\n"
        "- `low`: capability guessed from program/file naming conventions with limited supporting evidence\n\n"
        "## Instructions\n\n"
        "1. **Read all existing output artifacts:**\n"
        f"   - {output_dir}/application.md for current overview\n"
        f"   - {output_dir}/inventory/programs.md and {output_dir}/inventory/copybooks.md for scope\n"
        f"   - {output_dir}/data/data-dictionary.md for data entities\n"
        f"   - {output_dir}/business-rules/*.md for all per-program business rules\n"
        f"   - {output_dir}/flows/program-call-graph.md for topology\n"
        f"   - {output_dir}/flows/data-flows.md for data movement\n"
        f"   - {output_dir}/integration/interfaces.md for external boundaries\n\n"
        "2. **Derive functional capabilities:**\n"
        "   - Group related programs using the Capability Grouping Heuristics above\n"
        "   - Name each capability in business terms (not technical terms)\n"
        "   - Map each capability to its source programs, inputs, and outputs\n"
        "   - Identify the key business rules that govern each capability\n"
        "   - Assess complexity (number of programs, rules, integrations)\n\n"
        "3. **Derive non-functional requirements:**\n"
        "   - Use the NFR Indicators table above to scan for each category\n"
        "   - Error handling: graceful vs ABEND?\n"
        "   - Data integrity: transaction boundaries, commit/rollback patterns?\n"
        "   - Performance: sort steps, buffer/block sizes?\n"
        "   - Security: authentication/authorization checks?\n"
        "   - Audit/logging: DISPLAY statements, audit trail writes?\n"
        "   - Recovery: restart/checkpoint logic in batch programs?\n\n"
        "4. **Assess modernization considerations:**\n"
        "   - Use the Modernization Risk Indicators table above\n"
        "   - Complexity: total LOC, nesting depth\n"
        "   - Technical debt: GOTO-heavy programs, dead code, commented-out sections\n"
        "   - Decomposition candidates: loosely coupled program groups\n"
        "   - Data migration: file types, DB schemas, volume indicators\n"
        "   - Risks: tightly coupled programs, shared copybooks, complex REDEFINES\n\n"
        "5. **Update the application overview:**\n"
        f"   - Refine {output_dir}/application.md with purpose, tech stack, key observations\n\n"
        "6. **Write artifacts** to the output files:\n"
        f"   - {output_dir}/requirements/capabilities.md\n"
        f"   - {output_dir}/requirements/non-functional.md\n"
        f"   - {output_dir}/requirements/modernization-notes.md\n"
        f"   - Update {output_dir}/application.md\n\n"
        "   If output files already exist with pre-populated data, read them first.\n"
        "   Preserve existing frontmatter and table structure.\n\n"
        f"{_target_file_instruction(f'{output_dir}/requirements/capabilities.md', cross_cutting=True)}\n\n"
        "## Output Structure Reference\n\n"
        "Follow these canonical section headers and table columns for each artifact:\n\n"
        f"{_template_section('capabilities.md', f'{output_dir}/requirements/capabilities.md')}\n\n"
        f"{_template_section('non-functional.md', f'{output_dir}/requirements/non-functional.md')}\n\n"
        f"{_template_section('modernization-notes.md', f'{output_dir}/requirements/modernization-notes.md')}\n\n"
        f"{_template_section('application.md', f'{output_dir}/application.md')}\n\n"
        f"{draft_section}\n\n"
        "7. **Return discoveries** as JSON array.\n\n"
        "Return ONLY a JSON array (no markdown fences) of discovery objects with:\n"
        "discovery_type, artifact_type, artifact_path, summary, confidence"
    )
