"""Test-specifications prompt -- derives stack-agnostic behavioral tests from analysis artifacts."""

from __future__ import annotations

from pathlib import Path

from ._helpers import (
    _target_files_instruction,
    _template_section,
    _draft_status,
)


def build_test_specs_prompt(
    config: dict, program: str | None = None, *, workspace: Path | None = None
) -> str:
    output_dir = config.get("output", "./output")
    output_files = [
        f"{output_dir}/test-specs/behavioral-tests.md",
        f"{output_dir}/test-specs/data-contracts.md",
        f"{output_dir}/test-specs/equivalence-matrix.md",
    ]
    draft_section = _draft_status(output_files, workspace) if workspace else ""
    return (
        "You are a test specification analyst deriving stack-agnostic behavioral "
        "test specifications from COBOL reverse-engineering artifacts.\n\n"
        "## Anti-JOBOL Rules\n\n"
        "You are generating **stack-agnostic behavioral test specifications**. "
        "These tests will be implemented in whatever language and framework the "
        "target system uses. They describe WHAT the system does, not HOW.\n\n"
        "**MANDATORY rules:**\n"
        "- NEVER organize tests by COBOL program. Organize by business capability "
        "from `capabilities.md`\n"
        "- NEVER reference COBOL paragraph names, section names, or variable names "
        "in test scenario descriptions\n"
        "- NEVER describe test steps as COBOL execution paths "
        '("PERFORM X, then EVALUATE Y")\n'
        "- Use business domain language for all inputs and outputs. Map to legacy "
        "field names ONLY in the equivalence matrix\n"
        "- Each scenario must be implementable as a black-box test: given these "
        "inputs, expect these outputs\n"
        "- Include equivalence classes and boundary values derived from data "
        "dictionary field definitions (PIC clauses give you ranges)\n"
        "- For error scenarios, describe the expected behavior "
        '("rejects the transaction with an error indication") not the mechanism '
        '("moves \'E\' to WS-RESP-CD")\n\n'
        "## Scenario Derivation Heuristics\n\n"
        "| Business Rule Pattern | Test Scenario Type |\n"
        "| --- | --- |\n"
        "| IF condition THEN action | Happy-path (condition true) + error (condition false) |\n"
        "| EVALUATE with multiple WHEN branches | One scenario per branch + WHEN OTHER |\n"
        "| Numeric field with PIC 9(n) | Boundary: zero, max value (10^n - 1), negative if signed |\n"
        "| Alphanumeric field with valid values | Equivalence class per valid value + invalid value |\n"
        "| CALL/LINK returning success/failure codes | Happy-path (success) + one scenario per failure code |\n"
        "| Calculation (COMPUTE/ADD/SUBTRACT) | Verify formula with known inputs; boundary at overflow |\n"
        "| Date field (PIC 9(8) YYYYMMDD) | Valid date, invalid date, leap year boundary, zero/spaces |\n"
        "| Loop with counter | Zero iterations, one iteration, max iterations |\n\n"
        "## PIC Clause to Boundary Value Mapping\n\n"
        "| PIC Clause | Valid Range | Boundary Values |\n"
        "| --- | --- | --- |\n"
        "| PIC 9(n) | 0 to 10^n - 1 | 0, 1, 10^n - 1 |\n"
        "| PIC S9(n) | -(10^n - 1) to 10^n - 1 | -(10^n - 1), -1, 0, 1, 10^n - 1 |\n"
        "| PIC S9(n)V99 | Signed decimal | Min, -0.01, 0, 0.01, max |\n"
        "| PIC X(n) | Any character string, length n | Spaces, LOW-VALUES, all valid chars, max length |\n"
        "| PIC 9(8) (date) | YYYYMMDD date | 00000000, 19000101, 20240229 (leap), 99991231 |\n\n"
        "## Confidence Rules\n\n"
        "- `high`: test scenarios derived from explicit, unambiguous business rules "
        "with clear conditions and actions\n"
        "- `medium`: scenarios inferred from data flows or program behavior patterns; "
        "conditions are implicit or complex\n"
        "- `low`: scenarios based on naming conventions or structural patterns with "
        "limited supporting evidence; SME validation needed\n\n"
        "## Instructions\n\n"
        "1. **Read all existing output artifacts:**\n"
        f"   - {output_dir}/requirements/capabilities.md for capability groupings "
        "(primary organizing structure)\n"
        f"   - {output_dir}/business-rules/*.md for per-program business rules "
        "(primary source of test scenarios)\n"
        f"   - {output_dir}/data/data-dictionary.md for field types, ranges, and "
        "boundary values\n"
        f"   - {output_dir}/flows/data-flows.md for producer-consumer relationships "
        "and data transformation chains\n"
        f"   - {output_dir}/flows/program-call-graph.md for end-to-end call chains\n"
        f"   - {output_dir}/integration/interfaces.md for external integration "
        "boundaries\n\n"
        "   **Fallback:** If `capabilities.md` does not exist, infer capability "
        "groupings from the call graph (programs linked by CALL chains), data flows "
        "(programs sharing files/tables), and program naming patterns.\n\n"
        "2. **Derive behavioral test scenarios** for each capability:\n"
        "   - For every capability in capabilities.md, either write test "
        "scenarios or add an explicit note under the capability header "
        "explaining why it is excluded (e.g. batch-only data initialisation)\n"
        "   - Read the business rules for every program in the capability\n"
        "   - For each rule with a Condition and Action, derive at least one "
        "happy-path and one error scenario\n"
        "   - Use the Scenario Derivation Heuristics table above\n"
        "   - Use the PIC Clause to Boundary Value Mapping for boundary tests\n"
        "   - Every capability with at least one PIC-clause field must have "
        "at least one boundary test scenario\n"
        "   - Assign a unique scenario number within each capability\n"
        "   - Describe inputs and outputs in business-domain language\n"
        "   - Reference source rules by ID (e.g. rule numbers from the business "
        "rules tables), not by paragraph name\n\n"
        "3. **Derive data contract tests:**\n"
        "   - For each file, database table, and message queue in the data flows:\n"
        "     - Record layout invariants (field types, lengths, valid values)\n"
        "     - Key uniqueness and referential integrity rules\n"
        "     - Producer-consumer contracts (what a consumer expects from a producer)\n"
        "   - For cross-store invariants (e.g. account in DB must have corresponding "
        "customer in VSAM)\n"
        "   - When referencing transaction type codes, audit codes, or facility type "
        "values, resolve them to their actual literal values from the business rules "
        "(e.g. 'TFR' not 'transfer type')\n\n"
        "4. **Build the equivalence matrix:**\n"
        "   - For each test scenario, record the business rules and source programs "
        "it traces to\n"
        "   - Source Rules must use BR-PROGRAMNAME-N format (e.g. BR-ABNDPROC-1). "
        "If the business-rules file has numbered rules without BR- prefixes, create "
        "synthetic IDs using this pattern. Never use 'Capability-N'\n"
        "   - Include COBOL paragraph references HERE (this is the only place they "
        "belong)\n"
        "   - Source Paragraphs must include at least one specific paragraph name "
        "and line number. 'main section' and 'Multiple paragraphs' are not acceptable\n"
        "   - Compute coverage summary per capability\n"
        "   - Identify untested rules and document why\n\n"
        "5. **Derive cross-capability scenarios:**\n"
        "   - Identify data transformation chains from data-flows.md\n"
        "   - Create end-to-end test scenarios that verify correct data flow across "
        "capability boundaries\n"
        "   - Focus on chains where one capability's output is another's input\n\n"
        "6. **Write artifacts** to the output files:\n"
        f"   - {output_dir}/test-specs/behavioral-tests.md\n"
        f"   - {output_dir}/test-specs/data-contracts.md\n"
        f"   - {output_dir}/test-specs/equivalence-matrix.md\n\n"
        "   If output files already exist with pre-populated data, read them first.\n"
        "   Preserve existing frontmatter and table structure.\n\n"
        f"{_target_files_instruction(output_files)}\n\n"
        "## Output Structure Reference\n\n"
        "Follow these canonical section headers and table columns for each artifact:\n\n"
        f"{_template_section('behavioral-tests.md', f'{output_dir}/test-specs/behavioral-tests.md')}\n\n"
        f"{_template_section('data-contracts.md', f'{output_dir}/test-specs/data-contracts.md')}\n\n"
        f"{_template_section('equivalence-matrix.md', f'{output_dir}/test-specs/equivalence-matrix.md')}\n\n"
        f"{draft_section}\n\n"
        "7. **Return discoveries** as JSON array.\n\n"
        "Return ONLY a JSON array (no markdown fences) of discovery objects with:\n"
        "discovery_type, artifact_type, artifact_path, summary, confidence"
    )
